let fibonacciSequence = [];
fibonacciSequence.push(0);
fibonacciSequence.push(1);
fibonacciSequence.push(1);
fibonacciSequence.push(2);
fibonacciSequence.push(3);
fibonacciSequence.push(5);
fibonacciSequence.push(8);
console.log(fibonacciSequence[0]);
console.log(fibonacciSequence[1]);
console.log(fibonacciSequence[2]);
console.log(fibonacciSequence[3]);
console.log(fibonacciSequence[4]);
console.log(fibonacciSequence[5]);
console.log(fibonacciSequence[6]);